// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugvilvgsrupeoegealae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndmlsdmdzcnVwZW9lZ2VhbGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzcxNDYsImV4cCI6MjA1OTY1MzE0Nn0.mnxv7ErTifUNJCQNqB84B3YY8RF9jMRAn4aP7apsiYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);